"""Initial migration

Revision ID: 2f122fa1dde6
Revises: af21701cc8e1
Create Date: 2025-12-02 13:22:05.227675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f122fa1dde6'
down_revision: Union[str, None] = 'af21701cc8e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('batch_name', sa.String(), nullable=True),
    sa.Column('total_customers', sa.Integer(), nullable=False),
    sa.Column('input_file_url', sa.String(), nullable=True),
    sa.Column('output_file_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('avg_churn_probability', sa.String(), nullable=True),
    sa.Column('risk_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_batches_id'), 'prediction_batches', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_batches_organization_id'), 'prediction_batches', ['organization_id'], unique=False)
    op.create_table('customer_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('external_customer_id', sa.String(), nullable=False),
    sa.Column('churn_probability', sa.String(), nullable=False),
    sa.Column('risk_segment', sa.String(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('predicted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['prediction_batches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_predictions_batch_id'), 'customer_predictions', ['batch_id'], unique=False)
    op.create_index(op.f('ix_customer_predictions_external_customer_id'), 'customer_predictions', ['external_customer_id'], unique=False)
    op.create_index(op.f('ix_customer_predictions_id'), 'customer_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_customer_predictions_organization_id'), 'customer_predictions', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_predictions_organization_id'), table_name='customer_predictions')
    op.drop_index(op.f('ix_customer_predictions_id'), table_name='customer_predictions')
    op.drop_index(op.f('ix_customer_predictions_external_customer_id'), table_name='customer_predictions')
    op.drop_index(op.f('ix_customer_predictions_batch_id'), table_name='customer_predictions')
    op.drop_table('customer_predictions')
    op.drop_index(op.f('ix_prediction_batches_organization_id'), table_name='prediction_batches')
    op.drop_index(op.f('ix_prediction_batches_id'), table_name='prediction_batches')
    op.drop_table('prediction_batches')
    # ### end Alembic commands ###
