"""Initial migration

Revision ID: 61da4369659e
Revises: e32b7857f782
Create Date: 2025-12-02 11:21:55.148240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61da4369659e'
down_revision: Union[str, None] = 'e32b7857f782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('churn_threshold_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('external_customer_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_organization_id'), 'customers', ['organization_id'], unique=False)
    op.create_table('data_processing_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_processing_status_id'), 'data_processing_status', ['id'], unique=False)
    op.create_index(op.f('ix_data_processing_status_organization_id'), 'data_processing_status', ['organization_id'], unique=False)
    op.create_table('model_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('model_path', sa.String(), nullable=False),
    sa.Column('accuracy', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('precision', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('recall', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('roc_auc', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('feature_importance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_metadata_id'), 'model_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_model_metadata_organization_id'), 'model_metadata', ['organization_id'], unique=False)
    op.create_table('churn_predictions',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('churn_probability', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('risk_segment', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_churn_predictions_customer_id'), 'churn_predictions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_churn_predictions_organization_id'), 'churn_predictions', ['organization_id'], unique=False)
    op.create_table('customer_features',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('recency_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('frequency_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('monetary_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('engagement_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tenure_days', sa.Integer(), nullable=True),
    sa.Column('activity_trend', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_transaction_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('days_between_transactions', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_customer_features_customer_id'), 'customer_features', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_features_organization_id'), 'customer_features', ['organization_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_customer_id'), 'transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transactions_event_date'), 'transactions', ['event_date'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_organization_id'), 'transactions', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_organization_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_event_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_customer_features_organization_id'), table_name='customer_features')
    op.drop_index(op.f('ix_customer_features_customer_id'), table_name='customer_features')
    op.drop_table('customer_features')
    op.drop_index(op.f('ix_churn_predictions_organization_id'), table_name='churn_predictions')
    op.drop_index(op.f('ix_churn_predictions_customer_id'), table_name='churn_predictions')
    op.drop_table('churn_predictions')
    op.drop_index(op.f('ix_model_metadata_organization_id'), table_name='model_metadata')
    op.drop_index(op.f('ix_model_metadata_id'), table_name='model_metadata')
    op.drop_table('model_metadata')
    op.drop_index(op.f('ix_data_processing_status_organization_id'), table_name='data_processing_status')
    op.drop_index(op.f('ix_data_processing_status_id'), table_name='data_processing_status')
    op.drop_table('data_processing_status')
    op.drop_index(op.f('ix_customers_organization_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
