"""Initial migration

Revision ID: 8ad6670603fd
Revises: c5d8e9f1a2b3
Create Date: 2025-12-02 22:36:36.540362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad6670603fd'
down_revision: Union[str, None] = 'c5d8e9f1a2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_customer_segments_customer_id', 'customer_segments', type_='unique')
    op.add_column('datasets', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_datasets_is_active'), 'datasets', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datasets_is_active'), table_name='datasets')
    op.drop_column('datasets', 'is_active')
    op.create_unique_constraint('uq_customer_segments_customer_id', 'customer_segments', ['customer_id'])
    # ### end Alembic commands ###
