"""Initial migration

Revision ID: e32b7857f782
Revises: 4374dad262ef
Create Date: 2025-12-02 11:14:32.228417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e32b7857f782'
down_revision: Union[str, None] = '4374dad262ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('churn_threshold_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('data_processing_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_processing_status_id'), 'data_processing_status', ['id'], unique=False)
    op.create_index(op.f('ix_data_processing_status_organization_id'), 'data_processing_status', ['organization_id'], unique=False)
    op.create_table('model_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('model_path', sa.String(), nullable=False),
    sa.Column('accuracy', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('precision', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('recall', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('roc_auc', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('feature_importance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_metadata_id'), 'model_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_model_metadata_organization_id'), 'model_metadata', ['organization_id'], unique=False)
    op.create_table('churn_predictions',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('churn_probability', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('risk_segment', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_churn_predictions_customer_id'), 'churn_predictions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_churn_predictions_organization_id'), 'churn_predictions', ['organization_id'], unique=False)
    op.create_table('customer_features',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('recency_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('frequency_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('monetary_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('engagement_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tenure_days', sa.Integer(), nullable=True),
    sa.Column('activity_trend', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_transaction_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('days_between_transactions', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_customer_features_customer_id'), 'customer_features', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_features_organization_id'), 'customer_features', ['organization_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_customer_id'), 'transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transactions_event_date'), 'transactions', ['event_date'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_organization_id'), 'transactions', ['organization_id'], unique=False)
    op.drop_table('customer_behavior_summaries')
    op.drop_table('interventions')
    op.drop_index('ix_datasets_dataset_id', table_name='datasets')
    op.drop_table('datasets')
    op.add_column('customers', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.add_column('customers', sa.Column('external_customer_id', sa.String(), nullable=False))
    op.alter_column('customers', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_customers_customer_id', table_name='customers')
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_organization_id'), 'customers', ['organization_id'], unique=False)
    op.drop_constraint('customers_dataset_id_fkey', 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'organizations', ['organization_id'], ['id'])
    op.drop_column('customers', 'frequency_score')
    op.drop_column('customers', 'customer_segment')
    op.drop_column('customers', 'activity_count_30d')
    op.drop_column('customers', 'total_value_30d')
    op.drop_column('customers', 'support_tickets_30d')
    op.drop_column('customers', 'payment_failures')
    op.drop_column('customers', 'total_value_90d')
    op.drop_column('customers', 'updated_at')
    op.drop_column('customers', 'satisfaction_score')
    op.drop_column('customers', 'activity_count_90d')
    op.drop_column('customers', 'tenure_days')
    op.drop_column('customers', 'churn_risk_score')
    op.drop_column('customers', 'treatment_type')
    op.drop_column('customers', 'treatment')
    op.drop_column('customers', 'uplift_score')
    op.drop_column('customers', 'account_balance')
    op.drop_column('customers', 'engagement_score')
    op.drop_column('customers', 'session_count_30d')
    op.drop_column('customers', 'clv_estimate')
    op.drop_column('customers', 'customer_id')
    op.drop_column('customers', 'recency_score')
    op.drop_column('customers', 'monetary_score')
    op.drop_column('customers', 'activity_trend')
    op.drop_column('customers', 'outcome')
    op.drop_column('customers', 'dataset_id')
    op.drop_column('customers', 'feature_usage_count')
    op.drop_column('customers', 'rfm_score')
    op.drop_column('customers', 'avg_value_per_activity')
    op.drop_column('customers', 'original_data')
    op.drop_column('customers', 'days_since_last_activity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('days_since_last_activity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('original_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('avg_value_per_activity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('rfm_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('feature_usage_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('outcome', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('activity_trend', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('monetary_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('recency_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('customer_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('clv_estimate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('session_count_30d', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('engagement_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('account_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('uplift_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('treatment', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('treatment_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('churn_risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('tenure_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('activity_count_90d', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('satisfaction_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('total_value_90d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('payment_failures', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('support_tickets_30d', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('total_value_30d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('activity_count_30d', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('customer_segment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('frequency_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_foreign_key('customers_dataset_id_fkey', 'customers', 'datasets', ['dataset_id'], ['id'])
    op.drop_index(op.f('ix_customers_organization_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.create_index('ix_customers_customer_id', 'customers', ['customer_id'], unique=False)
    op.alter_column('customers', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('customers', 'external_customer_id')
    op.drop_column('customers', 'organization_id')
    op.create_table('datasets',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('datasets_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dataset_type', postgresql.ENUM('criteo', 'hillstrom', 'financial', 'b2b', 'custom', name='datasettype'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('uploading', 'processing', 'normalizing', 'completed', 'failed', name='datasetstatus'), autoincrement=False, nullable=True),
    sa.Column('original_filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_records', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('treatment_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('control_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('churn_rate_treatment', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('churn_rate_control', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('schema_mapping', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('processing_log', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('uploaded_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name='datasets_uploaded_by_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='datasets_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_datasets_dataset_id', 'datasets', ['dataset_id'], unique=True)
    op.create_table('interventions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('treatment_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('intervention_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('channel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uplift_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('expected_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('roi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('message_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message_body', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message_cta', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recommended_timing', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('executed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('customer_responded', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_retained', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actual_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('widget_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ab_test_variant', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='interventions_customer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='interventions_pkey')
    )
    op.create_table('customer_behavior_summaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lifecycle_stage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('customer_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('activity_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value_segment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('engagement_trend', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('preferred_channels', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_active_days_ago', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_frequency_per_month', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('risk_indicators', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('behavioral_trends', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recommended_interventions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('expected_retention_lift', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('intervention_roi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('summary_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='customer_behavior_summaries_customer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='customer_behavior_summaries_pkey'),
    sa.UniqueConstraint('customer_id', name='customer_behavior_summaries_customer_id_key')
    )
    op.drop_index(op.f('ix_transactions_organization_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_event_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_customer_features_organization_id'), table_name='customer_features')
    op.drop_index(op.f('ix_customer_features_customer_id'), table_name='customer_features')
    op.drop_table('customer_features')
    op.drop_index(op.f('ix_churn_predictions_organization_id'), table_name='churn_predictions')
    op.drop_index(op.f('ix_churn_predictions_customer_id'), table_name='churn_predictions')
    op.drop_table('churn_predictions')
    op.drop_index(op.f('ix_model_metadata_organization_id'), table_name='model_metadata')
    op.drop_index(op.f('ix_model_metadata_id'), table_name='model_metadata')
    op.drop_table('model_metadata')
    op.drop_index(op.f('ix_data_processing_status_organization_id'), table_name='data_processing_status')
    op.drop_index(op.f('ix_data_processing_status_id'), table_name='data_processing_status')
    op.drop_table('data_processing_status')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
