"""Initial migration

Revision ID: fa988e8195c0
Revises: 61da4369659e
Create Date: 2025-12-02 12:53:08.117918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa988e8195c0'
down_revision: Union[str, None] = '61da4369659e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_metadata', sa.Column('model_type', sa.String(), nullable=True))
    op.add_column('model_metadata', sa.Column('status', sa.String(), nullable=False))
    op.add_column('model_metadata', sa.Column('error_message', sa.String(), nullable=True))
    op.add_column('model_metadata', sa.Column('f1_score', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('model_metadata', sa.Column('training_samples', sa.Integer(), nullable=True))
    op.add_column('model_metadata', sa.Column('churn_rate', sa.Numeric(precision=5, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_metadata', 'churn_rate')
    op.drop_column('model_metadata', 'training_samples')
    op.drop_column('model_metadata', 'f1_score')
    op.drop_column('model_metadata', 'error_message')
    op.drop_column('model_metadata', 'status')
    op.drop_column('model_metadata', 'model_type')
    # ### end Alembic commands ###
