"""
Pydantic schemas for dynamic CSV normalization endpoint
"""

from typing import List, Tuple, Optional
from pydantic import BaseModel, Field


class SchemaField(BaseModel):
    """
    Represents a single field in the expected schema
    """
    column_name: str = Field(..., description="Name of the column in the output CSV")
    description: str = Field(..., description="Description of what this column represents")


class NormalizeRequest(BaseModel):
    """
    Request model for CSV normalization.

    Note: The CSV file is uploaded separately as multipart/form-data.
    This schema is for the expected_schema field.
    """
    expected_schema: List[SchemaField] = Field(
        ...,
        description="List of expected columns with their descriptions"
    )
    max_attempts: Optional[int] = Field(
        default=5,
        ge=1,
        le=10,
        description="Maximum number of attempts for LLM to generate valid script"
    )


class NormalizeResponse(BaseModel):
    """
    Response model for successful CSV normalization
    """
    success: bool = Field(..., description="Whether the normalization was successful")
    message: str = Field(..., description="Success or error message")
    output_csv_url: Optional[str] = Field(None, description="Public URL of the normalized CSV in Supabase")
    attempts: Optional[int] = Field(None, description="Number of attempts taken")
    generated_script: Optional[str] = Field(None, description="The Python script generated by LLM")
    error_details: Optional[dict] = Field(None, description="Error details if normalization failed")
